### ISSUE TITLE
Event not found

### ISSUE THREAD

**Issue by alittlebitofit** [jooert/matrix-displayname#1]
Hello, I tried your script but I get the following error:

bash: !asfLdzLnOdGRkdPZWu: event not found

That room ID is just a dummy one (from your example) and yes I used the original room ID I intended to.

Is this method outdated? Since I don't see `/_matrix/client/r0` in the URL.

Instead I see this: `https://riot.im/app/#/room/!asfLdzLnOdGRkdPZWu:example.org`

**Comment by jooert** [comment]
I haven't used this in a while, but in principle this should still work, as the API is still the same (see [spec](https://matrix.org/docs/spec/client_server/r0.4.0.html#put-matrix-client-r0-rooms-roomid-state-eventtype-statekey)). However, I would suggest using the new `/roomnick` command instead (see [PR](https://github.com/matrix-org/matrix-react-sdk/pull/2689)).

If you are still interested in debugging this, where do you see this:

> Instead I see this: https://riot.im/app/#/room/!asfLdzLnOdGRkdPZWu:example.org

This method communicates directly with a matrix homeserver and thus should be independent of Riot.

**Comment by alittlebitofit** [comment]
`/roomnick` command works.
I see the https URL in the address bar.

Can you please try your script again and see if it still works?

**Comment by jooert** [comment]
I just tried it for myself, it still works for me. I suppose you have to quote the room name, because the exclamation mark `!` is a special character in bash.

**Comment by alittlebitofit** [comment]
Did you mean room "ID" instead of room "name" ?
If yes, then yes I quoted the room ID and still find the same `bash: [room ID]: event not found` error.

**Comment by alittlebitofit** [comment]
You know what worked! Escaping the `!`.

You just need a backslash before the exclamation mark. `\!`

Maybe you did put the backslash in the example command but it got escaped too. 😅

And one more thing, you don't need to quote the room ID, just escape the `!`.

So the whole command that worked for _**me**_ is:

`./set_displayname \!asfLdzLnOdGRkdPZWu:example.org "John Doe" "@johndoe:example.org" [password]`


And thanks for the script ^^.

**Comment by jooert** [comment]
Yes, I meant the room ID. Glad, that you got the script to work! Actually, it also works with quoting, but you need to use single quotes instead of double ones. I use [fish-shell](https://github.com/fish-shell/fish-shell) where the exclamation mark is no special character that's why it worked for me.
